package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	localesDir := "./locales" // assume run from project root
	outputFile := "./pkg/translations/keys.go"

	constHeader := `package translations

// Code generated by generate_translations.go; DO NOT EDIT.

type Key string

const (
`
	constFooter := ")\n"

	keys := make(map[string]struct{})

	// Check if locales folder exists
	if _, err := os.Stat(localesDir); os.IsNotExist(err) {
		panic("folder 'locales' not found: " + localesDir)
	}

	// Walk each language folder
	langs, err := os.ReadDir(localesDir)
	if err != nil {
		panic(err)
	}

	for _, langDir := range langs {
		if !langDir.IsDir() {
			continue
		}
		langPath := filepath.Join(localesDir, langDir.Name())
		moduleFiles, err := os.ReadDir(langPath)
		if err != nil {
			panic(err)
		}
		for _, f := range moduleFiles {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
				continue
			}
			path := filepath.Join(langPath, f.Name())
			data, err := os.ReadFile(path)
			if err != nil {
				panic(err)
			}
			var messages map[string]string
			if err := json.Unmarshal(data, &messages); err != nil {
				panic(err)
			}
			// store all keys
			for key := range messages {
				keys[key] = struct{}{}
			}
		}
	}

	// Convert map keys to slice & sort for deterministic order
	var sortedKeys []string
	for k := range keys {
		sortedKeys = append(sortedKeys, k)
	}
	sort.Strings(sortedKeys)

	// Write constants file
	file, err := os.Create(outputFile)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	file.WriteString(constHeader)
	for _, key := range sortedKeys {
		constName := formatConstName(key)
		file.WriteString(fmt.Sprintf("\t%s Key = \"%s\"\n", constName, key))
	}
	file.WriteString(constFooter)

	fmt.Println("Generated keys.go with", len(sortedKeys), "keys.")
}

// formatConstName converts JSON key to Go constant style
func formatConstName(key string) string {
	constName := strings.ReplaceAll(key, ".", "_")
	constName = strings.ReplaceAll(constName, "-", "_")
	constName = strings.ToUpper(constName)
	return constName
}
